SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS i JOIN 
(SELECT ANIMAL_ID FROM ANIMAL_OUTS WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%') o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE SEX_UPON_INTAKE LIKE 'Intact%'
ORDER BY o.ANIMAL_ID
