SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, r.SCORE
FROM REST_INFO i LEFT JOIN 
(SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) SCORE FROM REST_REVIEW
GROUP BY REST_ID)
r ON i.REST_ID = r.REST_ID
WHERE i.ADDRESS LIKE '서울%' AND SCORE IS NOT NULL
ORDER BY r.SCORE DESC, i.FAVORITES DESC;